"""RSP-aligned Risk Report generator.

Generates safety risk reports aligned with Anthropic's Responsible
Scaling Policy (RSP) v3.0 framework. Produces structured assessments
covering threat models, safety profiles, and risk mitigations.

Usage:
    from sentinel.rsp_report import RiskReportGenerator

    generator = RiskReportGenerator()
    report = generator.generate(texts=["user input 1", "user input 2"])
    print(report.to_markdown())
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Sequence

from sentinel.core import SentinelGuard, ScanResult, RiskLevel


@dataclass
class ThreatAssessment:
    domain: str
    description: str
    risk_level: RiskLevel
    findings_count: int
    mitigations: list[str]


@dataclass
class RiskReport:
    """Structured risk report aligned with Anthropic RSP v3.0."""

    generated_at: str
    total_scans: int
    overall_risk: RiskLevel
    blocked_count: int
    threat_assessments: list[ThreatAssessment]
    risk_distribution: dict[str, int]
    category_breakdown: dict[str, int]
    scan_latency_avg_ms: float
    recommendations: list[str]

    def to_markdown(self) -> str:
        lines = [
            "# Safety Risk Report",
            f"*Generated: {self.generated_at}*",
            "",
            "## Executive Summary",
            "",
            f"- **Overall Risk Level**: {self.overall_risk.value.upper()}",
            f"- **Total Scans**: {self.total_scans}",
            f"- **Content Blocked**: {self.blocked_count}",
            f"- **Avg Scan Latency**: {self.scan_latency_avg_ms:.2f}ms",
            "",
            "## Risk Distribution",
            "",
            "| Risk Level | Count |",
            "|------------|-------|",
        ]
        for level in ["critical", "high", "medium", "low", "none"]:
            count = self.risk_distribution.get(level, 0)
            lines.append(f"| {level.upper()} | {count} |")

        lines.extend([
            "",
            "## Threat Domain Assessments",
            "",
        ])

        for assessment in self.threat_assessments:
            lines.extend([
                f"### {assessment.domain}",
                "",
                f"**Risk Level**: {assessment.risk_level.value.upper()}  ",
                f"**Findings**: {assessment.findings_count}",
                "",
                assessment.description,
                "",
            ])
            if assessment.mitigations:
                lines.append("**Active Mitigations:**")
                for m in assessment.mitigations:
                    lines.append(f"- {m}")
                lines.append("")

        if self.category_breakdown:
            lines.extend([
                "## Finding Categories",
                "",
                "| Category | Count |",
                "|----------|-------|",
            ])
            for cat, count in sorted(
                self.category_breakdown.items(),
                key=lambda x: x[1],
                reverse=True,
            ):
                lines.append(f"| {cat} | {count} |")
            lines.append("")

        if self.recommendations:
            lines.extend([
                "## Recommendations",
                "",
            ])
            for i, rec in enumerate(self.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        lines.extend([
            "---",
            "*Report generated by Sentinel AI — aligned with "
            "Anthropic Responsible Scaling Policy (RSP) v3.0 framework.*",
        ])

        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "generated_at": self.generated_at,
            "total_scans": self.total_scans,
            "overall_risk": self.overall_risk.value,
            "blocked_count": self.blocked_count,
            "threat_assessments": [
                {
                    "domain": a.domain,
                    "description": a.description,
                    "risk_level": a.risk_level.value,
                    "findings_count": a.findings_count,
                    "mitigations": a.mitigations,
                }
                for a in self.threat_assessments
            ],
            "risk_distribution": self.risk_distribution,
            "category_breakdown": self.category_breakdown,
            "scan_latency_avg_ms": self.scan_latency_avg_ms,
            "recommendations": self.recommendations,
        }


# Mapping from scanner categories to RSP threat domains
_CATEGORY_TO_DOMAIN = {
    "prompt_injection": "Model Misuse & Prompt Attacks",
    "pii": "Data Privacy & Information Security",
    "harmful_content": "Dangerous Capabilities & Content Safety",
    "toxicity": "Output Safety & Content Integrity",
    "hallucination": "Output Reliability & Factual Accuracy",
    "tool_use": "Agentic Safety & Tool-Use Risks",
    "blocked_terms": "Policy Compliance",
}

_DOMAIN_DESCRIPTIONS = {
    "Model Misuse & Prompt Attacks": (
        "Assesses attempts to manipulate model behavior through prompt "
        "injection, jailbreaks, role injection, and instruction override. "
        "Aligns with RSP threat models for model misuse by adversarial actors."
    ),
    "Data Privacy & Information Security": (
        "Evaluates exposure of personally identifiable information (PII) "
        "including credentials, API keys, and sensitive personal data. "
        "Supports compliance with data protection requirements."
    ),
    "Dangerous Capabilities & Content Safety": (
        "Detects requests for or generation of content related to weapons, "
        "chemical/biological threats, self-harm, and other dangerous "
        "capabilities. Directly maps to RSP catastrophic risk categories."
    ),
    "Output Safety & Content Integrity": (
        "Monitors for toxic outputs including threats, severe insults, "
        "and aggressive language that could cause harm."
    ),
    "Output Reliability & Factual Accuracy": (
        "Identifies hallucination signals: fabricated citations, false "
        "confidence markers, and self-contradictions that undermine "
        "output reliability."
    ),
    "Agentic Safety & Tool-Use Risks": (
        "Scans tool calls and commands for dangerous operations including "
        "shell injection, data exfiltration, privilege escalation, and "
        "destructive file operations. Critical for agentic AI safety."
    ),
    "Policy Compliance": (
        "Checks for organization-specific blocked terms and phrases "
        "to enforce custom content policies."
    ),
}

_DOMAIN_MITIGATIONS = {
    "Model Misuse & Prompt Attacks": [
        "Pattern-based injection detection with multi-category coverage",
        "Delimiter injection scanning (ChatML, INST, SYS tags)",
        "Jailbreak keyword and technique detection",
        "Context manipulation detection for multi-turn attacks",
        "Encoding/obfuscation bypass detection",
    ],
    "Data Privacy & Information Security": [
        "Real-time PII detection with automatic redaction",
        "Luhn-validated credit card number detection",
        "API key and token pattern matching (AWS, GitHub, Slack)",
        "SSN, email, and phone number scanning",
    ],
    "Dangerous Capabilities & Content Safety": [
        "Weapons/explosive content detection",
        "Chemical and biological threat content blocking",
        "Self-harm content detection and blocking",
        "Fraud and hacking instruction detection",
    ],
    "Output Safety & Content Integrity": [
        "Threat and violent language detection",
        "Severe insult and derogatory language filtering",
        "Profanity detection with configurable risk levels",
        "Aggressive tone analysis",
    ],
    "Output Reliability & Factual Accuracy": [
        "Fabricated citation detection",
        "False confidence marker identification",
        "Self-contradiction signal detection",
    ],
    "Agentic Safety & Tool-Use Risks": [
        "Dangerous shell command detection (rm -rf, dd, mkfs)",
        "Network exfiltration pattern matching",
        "Sensitive file access monitoring",
        "Privilege escalation detection",
        "Reverse shell and backdoor detection",
    ],
    "Policy Compliance": [
        "Custom blocked term enforcement",
        "Configurable per-organization policies",
    ],
}


class RiskReportGenerator:
    """Generate RSP-aligned risk reports from scan results."""

    def __init__(self, guard: SentinelGuard | None = None):
        self._guard = guard or SentinelGuard.default()

    def generate(
        self,
        texts: Sequence[str] | None = None,
        scan_results: Sequence[ScanResult] | None = None,
    ) -> RiskReport:
        """Generate a risk report from texts or pre-computed scan results."""
        if scan_results is None:
            if texts is None:
                raise ValueError("Provide either texts or scan_results")
            scan_results = [self._guard.scan(t) for t in texts]

        results = list(scan_results)

        # Aggregate metrics
        total = len(results)
        blocked = sum(1 for r in results if r.blocked)
        latency_avg = (
            sum(r.latency_ms for r in results) / total if total > 0 else 0.0
        )

        # Risk distribution
        risk_dist: dict[str, int] = {}
        for r in results:
            level = r.risk.value
            risk_dist[level] = risk_dist.get(level, 0) + 1

        # Category breakdown
        category_counts: dict[str, int] = {}
        for r in results:
            for f in r.findings:
                category_counts[f.category] = (
                    category_counts.get(f.category, 0) + 1
                )

        # Overall risk
        overall = RiskLevel.NONE
        for r in results:
            if r.risk > overall:
                overall = r.risk

        # Threat domain assessments
        domain_findings: dict[str, int] = {}
        domain_max_risk: dict[str, RiskLevel] = {}
        for r in results:
            for f in r.findings:
                domain = _CATEGORY_TO_DOMAIN.get(f.category, "Other")
                domain_findings[domain] = domain_findings.get(domain, 0) + 1
                current = domain_max_risk.get(domain, RiskLevel.NONE)
                if f.risk > current:
                    domain_max_risk[domain] = f.risk

        # Build assessments for all domains
        assessments = []
        for domain in _DOMAIN_DESCRIPTIONS:
            count = domain_findings.get(domain, 0)
            risk = domain_max_risk.get(domain, RiskLevel.NONE)
            assessments.append(
                ThreatAssessment(
                    domain=domain,
                    description=_DOMAIN_DESCRIPTIONS[domain],
                    risk_level=risk,
                    findings_count=count,
                    mitigations=_DOMAIN_MITIGATIONS.get(domain, []),
                )
            )

        # Sort by risk level (highest first)
        risk_order = list(RiskLevel)
        assessments.sort(
            key=lambda a: risk_order.index(a.risk_level), reverse=True
        )

        # Generate recommendations
        recommendations = self._generate_recommendations(
            overall, category_counts, blocked, total
        )

        return RiskReport(
            generated_at=datetime.now(timezone.utc).strftime(
                "%Y-%m-%d %H:%M:%S UTC"
            ),
            total_scans=total,
            overall_risk=overall,
            blocked_count=blocked,
            threat_assessments=assessments,
            risk_distribution=risk_dist,
            category_breakdown=category_counts,
            scan_latency_avg_ms=round(latency_avg, 2),
            recommendations=recommendations,
        )

    @staticmethod
    def _generate_recommendations(
        overall: RiskLevel,
        categories: dict[str, int],
        blocked: int,
        total: int,
    ) -> list[str]:
        recs = []

        if categories.get("prompt_injection", 0) > 0:
            recs.append(
                "Implement input validation and prompt hardening to reduce "
                "injection attack surface"
            )
        if categories.get("pii", 0) > 0:
            recs.append(
                "Enable automatic PII redaction in production pipelines "
                "to prevent data leakage"
            )
        if categories.get("harmful_content", 0) > 0:
            recs.append(
                "Review content policy configuration and ensure harmful "
                "content blocking is enabled at appropriate thresholds"
            )
        if categories.get("tool_use", 0) > 0:
            recs.append(
                "Audit agentic tool-use permissions and restrict shell "
                "execution to allowlisted commands"
            )
        if categories.get("hallucination", 0) > 0:
            recs.append(
                "Consider adding retrieval-augmented generation (RAG) or "
                "citation verification for factual accuracy"
            )
        if categories.get("toxicity", 0) > 0:
            recs.append(
                "Review output filtering thresholds for toxicity and "
                "adjust profanity risk levels for your use case"
            )
        if blocked > 0 and total > 0:
            block_rate = blocked / total * 100
            recs.append(
                f"Block rate is {block_rate:.1f}% — review blocked content "
                f"to calibrate sensitivity thresholds"
            )
        if overall >= RiskLevel.HIGH:
            recs.append(
                "Overall risk is HIGH or above — consider escalation "
                "procedures and incident response planning"
            )
        if not recs:
            recs.append("No significant risks detected in this assessment")

        return recs
